name: "📚 Documentation Update"
description: "Request improvements or additions to documentation"
title: "[Docs] "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What part of the docs needs updating?
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed Changes
      description: What should be changed or added?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, screenshots, or examples.
